
export const REQUEST_PLAYING_MOVIE = 'REQUEST_PLAYING_MOVIE'
export const REQUEST_PLAYING_MOVIE_ERROR = 'REQUEST_PLAYING_MOVIE_ERROR'
export const REQUEST_COMING_MOVIE = 'REQUEST_COMING_MOVIE'
export const REQUEST_COMING_MOVIE_ERROR = 'REQUEST_COMING_MOVIE_ERROR'

export const REQUEST_FILM = 'REQUEST_FILM'
export const REQUEST_FILM_ERROR = 'REQUEST_FILM_ERROR'
export const CLEAR_FILM = 'CLEAR_FILM'

export const GET_TITLE = 'GET_TITLE'
export const GET_PAGE_TITLE = 'GET_PAGE_TITLE'

export const LOADING = 'LOADING'
export const LOAD_FINISHED = 'LOAD_FINISHED'

export const GET_CINEMA_LIST = 'GET_CINEMA_LIST'
export const GET_CINEMA_LIST_ERROR = 'GET_CINEMA_LIST_ERROR'
